In [41]:
import tensorflow as tf
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import SGDClassifier
from sklearn import metrics

In [42]:
training_size = 12000
testing_size = 1000

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()
x_train = x_train[0:training_size]
y_train = y_train[0:training_size]

x_test = x_test[0:testing_size]
y_test = y_test[0:testing_size]

x_train = [x_train[i].reshape(-1,) for i in range(training_size)] 
x_test = [x_test[i].reshape(-1,) for i in range(testing_size)]


In [43]:

KNN = KNeighborsClassifier(
    n_neighbors=5,
    algorithm='auto',
    leaf_size=30,
    metric='minkowski',
    p=1,
    metric_params=None,
    n_jobs=None
)

KNN.fit(x_train, y_train)
result = KNN.predict(x_test)
print('Accuracy: ', metrics.accuracy_score(y_test, result))
print('Precision: ', metrics.precision_score(y_test, result, average='weighted'))
print('Recall: ', metrics.recall_score(y_test, result, average='weighted'))
print('F1 Score: ', metrics.f1_score(y_test, result, average='weighted'))

metrics.confusion_matrix(y_test, result)

Accuracy:  0.83
Precision:  0.8335518064574142
Recall:  0.83
F1 Score:  0.8299426671612983


array([[ 89,   0,   1,   3,   0,   0,  14,   0,   0,   0],
       [  1, 102,   0,   1,   1,   0,   0,   0,   0,   0],
       [  3,   0,  90,   0,   8,   0,  10,   0,   0,   0],
       [  8,   1,   0,  77,   5,   0,   2,   0,   0,   0],
       [  0,   0,  19,   5,  80,   0,  11,   0,   0,   0],
       [  0,   0,   0,   0,   0,  73,   0,   8,   0,   6],
       [ 20,   0,  16,   2,   8,   0,  51,   0,   0,   0],
       [  0,   0,   0,   0,   0,   1,   0,  86,   0,   8],
       [  0,   0,   0,   0,   1,   0,   3,   0,  91,   0],
       [  0,   0,   0,   0,   0,   0,   0,   4,   0,  91]])

In [44]:
DTC = DecisionTreeClassifier(
    criterion='entropy',
    splitter='best',
    max_depth=10,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features=None,
    random_state=None,
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    class_weight=None,
    ccp_alpha=0.0)

DTC.fit(x_train, y_train)
result = DTC.predict(x_test)
print('Accuracy: ', metrics.accuracy_score(y_test, result))
print('Precision: ', metrics.precision_score(y_test, result, average='weighted'))
print('Recall: ', metrics.recall_score(y_test, result, average='weighted'))
print('F1 Score: ', metrics.f1_score(y_test, result, average='weighted'))

metrics.confusion_matrix(y_test, result)

Accuracy:  0.807
Precision:  0.80590133619678
Recall:  0.807
F1 Score:  0.8056017556147596


array([[86,  0,  2,  5,  0,  0, 11,  1,  2,  0],
       [ 1, 98,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 3,  1, 78,  1, 16,  0, 11,  0,  1,  0],
       [ 6,  2,  0, 77,  4,  1,  1,  0,  0,  2],
       [ 1,  0, 19,  1, 85,  0,  9,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 74,  0,  8,  4,  1],
       [15,  1, 14,  5, 13,  0, 48,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  3,  0, 89,  0,  3],
       [ 0,  1,  2,  0,  0,  1,  3,  1, 87,  0],
       [ 0,  0,  0,  0,  0,  2,  0,  8,  0, 85]])

In [45]:
SGD = SGDClassifier(
    loss='hinge',
    penalty='l2'
)

SGD.fit(x_train, y_train)
result = SGD.predict(x_test)
print('Accuracy: ', metrics.accuracy_score(y_test, result))
print('Precision: ', metrics.precision_score(y_test, result, average='weighted'))
print('Recall: ', metrics.recall_score(y_test, result, average='weighted'))
print('F1 Score: ', metrics.f1_score(y_test, result, average='weighted'))

metrics.confusion_matrix(y_test, result)

Accuracy:  0.807
Precision:  0.8096754322260206
Recall:  0.807
F1 Score:  0.8045094905297903


array([[ 79,   2,   4,   6,   0,   0,  12,   0,   4,   0],
       [  0, 101,   0,   4,   0,   0,   0,   0,   0,   0],
       [  2,   1,  89,   1,   8,   0,  10,   0,   0,   0],
       [  2,   5,   3,  73,   3,   0,   3,   0,   4,   0],
       [  1,   0,  21,   9,  79,   0,   5,   0,   0,   0],
       [  0,   1,   0,   1,   0,  70,   1,   5,   5,   4],
       [  7,   0,  21,   4,  12,   0,  47,   0,   6,   0],
       [  0,   0,   0,   0,   0,   2,   0,  87,   1,   5],
       [  1,   0,   1,   0,   1,   0,   0,   0,  92,   0],
       [  0,   0,   0,   0,   0,   0,   0,   4,   1,  90]])

The accuracy of the all three classifiers are lower than that found in the Fashion-MINST paper. This is due to the smaller training sample.